server:
  port: 9090
logging:
  level:
    com.microservice.usuarioexterno: DEBUG
    org.springboot: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: mscv-usuarioexterno
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:h2:mem:banco
#    driverClassName: org.h2.Driver
#    username: sa
#    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

